# Generated by Django 4.2 on 2025-06-20 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("adminprofile", "0006_customuser_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GCalIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refresh_token", models.CharField(max_length=255)),
                ("access_token", models.CharField(max_length=255)),
                ("expiration_time", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adminprofile.barber",
                    ),
                ),
            ],
        ),
    ]
