# Generated by Django 4.2 on 2025-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gcalintegration",
            name="refresh_token",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
