# Generated by Django 5.0 on 2025-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_alter_gcalintegration_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="gcalintegration",
            name="calendar_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
