# Generated by Django 5.0 on 2025-09-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
