# Generated by Django 5.0 on 2025-09-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_booking_end_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="event_id", new_name="eventid",
        ),
    ]
