# Generated by Django 5.0 on 2025-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0006_rename_event_id_booking_eventid"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="name",
            field=models.CharField(max_length=75, null=True),
        ),
    ]
