# Generated by Django 4.2 on 2025-04-11 23:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barber",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("adminprofile.customuser",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("adminprofile.customuser",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("BARBER", "Barber"), ("CLIENT", "Client")],
                default="BARBER",
                max_length=50,
            ),
        ),
    ]
