# Generated by Django 4.2 on 2025-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminprofile", "0003_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="image_url",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
