# Generated by Django 4.2 on 2025-04-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminprofile", "0004_alter_services_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
