# Generated by Django 5.0 on 2025-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminprofile", "0006_customuser_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services", name="price", field=models.IntegerField(default=0),
        ),
    ]
