# Generated by Django 5.0 on 2026-08-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminprofile", "0007_alter_services_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="twilio_phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
