# Generated by Django 5.0 on 2026-09-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminprofile", "0008_customuser_twilio_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_platform_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
